"""Add kids_narration_url

Revision ID: 15f922634d0b
Revises: a983726194c6
Create Date: 2026-01-30 23:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '15f922634d0b'
down_revision = 'a983726194c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narrations', sa.Column('kids_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('narrations', 'kids_url')
    # ### end Alembic commands ###
