"""pr11_narrations

Revision ID: 2e5840debe89
Revises: 0009_pr10_deletion
Create Date: 2026-01-25 11:15:25.854140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e5840debe89'
down_revision: Union[str, None] = '0009_pr10_deletion'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poi_id', sa.Uuid(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filesize_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrations_poi_id'), 'narrations', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys', ...) removed
    op.drop_index(op.f('ix_narrations_poi_id'), table_name='narrations')
    op.drop_table('narrations')
    # ### end Alembic commands ###
