"""funnel_tables

Revision ID: 52efc9dc259e
Revises: 5240eae4e400
Create Date: 2026-01-28 20:09:18.130608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52efc9dc259e'
down_revision: Union[str, None] = '5240eae4e400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funnel_conversions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('funnel_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_conversions_date'), 'funnel_conversions', ['date'], unique=False)
    op.create_index(op.f('ix_funnel_conversions_funnel_id'), 'funnel_conversions', ['funnel_id'], unique=False)
    op.create_table('funnel_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('funnel_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_steps_funnel_id'), 'funnel_steps', ['funnel_id'], unique=False)
    # op.drop_table('spatial_ref_sys')  # Commented out: cannot drop because extension postgis requires it
    op.drop_index(op.f('ix_entitlement_grants_source_ref_lookup'), table_name='entitlement_grants')
    op.drop_index(op.f('uq_entitlement_grants_source_source_ref'), table_name='entitlement_grants')
    op.create_index(op.f('ix_entitlement_grants_source_ref'), 'entitlement_grants', ['source_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitlement_grants_source_ref'), table_name='entitlement_grants')
    op.create_index(op.f('uq_entitlement_grants_source_source_ref'), 'entitlement_grants', ['source', 'source_ref'], unique=True)
    op.create_index(op.f('ix_entitlement_grants_source_ref_lookup'), 'entitlement_grants', ['source_ref'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_funnel_steps_funnel_id'), table_name='funnel_steps')
    op.drop_table('funnel_steps')
    op.drop_index(op.f('ix_funnel_conversions_funnel_id'), table_name='funnel_conversions')
    op.drop_index(op.f('ix_funnel_conversions_date'), table_name='funnel_conversions')
    op.drop_table('funnel_conversions')
    op.drop_table('funnels')
    # ### end Alembic commands ###
