"""pr20_entitlement_grant_schema

Revision ID: a74747f06d86
Revises: 9a912b94ce88
Create Date: 2026-01-25 22:52:51.802918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a74747f06d86'
down_revision: Union[str, None] = '9a912b94ce88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlement_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_anon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entitlement_id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlement_grants_device_anon_id'), 'entitlement_grants', ['device_anon_id'], unique=False)
    op.create_index(op.f('ix_entitlement_grants_entitlement_id'), 'entitlement_grants', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_entitlement_grants_source_ref'), 'entitlement_grants', ['source_ref'], unique=True)
    op.create_index(op.f('ix_entitlement_grants_user_id'), 'entitlement_grants', ['user_id'], unique=False)
    op.add_column('entitlements', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entitlements', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entitlements', sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entitlements', sa.Column('title_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entitlements', sa.Column('price_amount', sa.Float(), nullable=False))
    op.add_column('entitlements', sa.Column('price_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entitlements', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_entitlements_city_slug'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_device_anon_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_tour_id'), table_name='entitlements')
    op.create_index(op.f('ix_entitlements_slug'), 'entitlements', ['slug'], unique=True)
    op.drop_column('entitlements', 'tour_id')
    op.drop_column('entitlements', 'city_slug')
    op.drop_column('entitlements', 'granted_at')
    op.drop_column('entitlements', 'revoked_at')
    op.drop_column('entitlements', 'device_anon_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlements', sa.Column('device_anon_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('entitlements', sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('entitlements', sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('entitlements', sa.Column('city_slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('entitlements', sa.Column('tour_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_entitlements_slug'), table_name='entitlements')
    op.create_index(op.f('ix_entitlements_tour_id'), 'entitlements', ['tour_id'], unique=False)
    op.create_index(op.f('ix_entitlements_device_anon_id'), 'entitlements', ['device_anon_id'], unique=False)
    op.create_index(op.f('ix_entitlements_city_slug'), 'entitlements', ['city_slug'], unique=False)
    op.drop_column('entitlements', 'is_active')
    op.drop_column('entitlements', 'price_currency')
    op.drop_column('entitlements', 'price_amount')
    op.drop_column('entitlements', 'title_ru')
    op.drop_column('entitlements', 'ref')
    op.drop_column('entitlements', 'scope')
    op.drop_column('entitlements', 'slug')
    op.drop_index(op.f('ix_entitlement_grants_user_id'), table_name='entitlement_grants')
    op.drop_index(op.f('ix_entitlement_grants_source_ref'), table_name='entitlement_grants')
    op.drop_index(op.f('ix_entitlement_grants_entitlement_id'), table_name='entitlement_grants')
    op.drop_index(op.f('ix_entitlement_grants_device_anon_id'), table_name='entitlement_grants')
    op.drop_table('entitlement_grants')
    # ### end Alembic commands ###
