"""Add itineraries

Revision ID: a983726194c6
Revises: 2026_optimize_indexes
Create Date: 2026-01-30 22:51:38.674557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a983726194c6'
down_revision: Union[str, None] = '2026_optimize_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_anon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_city_slug'), 'itineraries', ['city_slug'], unique=False)
    op.create_index(op.f('ix_itineraries_device_anon_id'), 'itineraries', ['device_anon_id'], unique=False)
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    
    op.create_table('itinerary_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_items_itinerary_id'), 'itinerary_items', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_poi_id'), 'itinerary_items', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_items_poi_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_itinerary_id'), table_name='itinerary_items')
    op.drop_table('itinerary_items')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_device_anon_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_city_slug'), table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
