"""pr12_osm_id

Revision ID: e5a6b272c889
Revises: 2e5840debe89
Create Date: 2026-01-25 11:33:18.689243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5a6b272c889'
down_revision: Union[str, None] = '2e5840debe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys') - skipped
    op.add_column('poi', sa.Column('osm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_poi_osm_id'), 'poi', ['osm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poi_osm_id'), table_name='poi')
    op.drop_column('poi', 'osm_id')
    # op.create_table('spatial_ref_sys') - skipped
    # ### end Alembic commands ###
