"""pr22_caching_updated_at

Revision ID: e72429370f4b
Revises: a74747f06d86
Create Date: 2026-01-25 23:30:56.911889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e72429370f4b'
down_revision: Union[str, None] = 'a74747f06d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('poi', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_poi_updated_at'), 'poi', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poi_updated_at'), table_name='poi')
    op.drop_column('poi', 'updated_at')
    op.drop_column('city', 'updated_at')
    # ### end Alembic commands ###
