"""content_versions

Revision ID: eb40eae4e200
Revises: dac0eae4e100
Create Date: 2026-01-28 12:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb40eae4e200'
down_revision: Union[str, None] = 'dac0eae4e100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_versions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('poi_id', sa.Uuid(), nullable=False),
        sa.Column('version_at', sa.DateTime(), nullable=False),
        sa.Column('changed_by', sa.Uuid(), nullable=True),
        sa.Column('title_ru', sa.String(), nullable=False),
        sa.Column('description_ru', sa.String(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lon', sa.Float(), nullable=True),
        sa.Column('full_snapshot_json', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_versions_poi_id'), 'poi_versions', ['poi_id'], unique=False)
    
    op.create_table('tour_versions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tour_id', sa.Uuid(), nullable=False),
        sa.Column('version_at', sa.DateTime(), nullable=False),
        sa.Column('changed_by', sa.Uuid(), nullable=True),
        sa.Column('title_ru', sa.String(), nullable=False),
        sa.Column('description_ru', sa.String(), nullable=True),
        sa.Column('full_snapshot_json', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_versions_tour_id'), 'tour_versions', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_versions_tour_id'), table_name='tour_versions')
    op.drop_table('tour_versions')
    op.drop_index(op.f('ix_poi_versions_poi_id'), table_name='poi_versions')
    op.drop_table('poi_versions')
    # ### end Alembic commands ###
