"""content_issues

Revision ID: fc50eae4e300
Revises: eb40eae4e200
Create Date: 2026-01-28 12:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc50eae4e300'
down_revision: Union[str, None] = 'eb40eae4e200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_validation_issues',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('issue_type', sa.String(), nullable=False),
        sa.Column('severity', sa.String(), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('fixed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_validation_issues_entity_type'), 'content_validation_issues', ['entity_type'], unique=False)
    op.create_index(op.f('ix_content_validation_issues_entity_id'), 'content_validation_issues', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_validation_issues_entity_id'), table_name='content_validation_issues')
    op.drop_index(op.f('ix_content_validation_issues_entity_type'), table_name='content_validation_issues')
    op.drop_table('content_validation_issues')
    # ### end Alembic commands ###
