targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: false
          scoped_dart_components: true
      riverpod_generator:
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
